### ISSUE TITLE
Expose `--disable-cloud-provider` feature and `cloud-provider=` kubelet arg

### ISSUE THREAD

**Issue by anmazzotti** [k3s-io/cluster-api-k3s#106]
The current implementation of `DisableExternalCloudProvider` is a bit confusing (sorry for that). 

As discussed in [this comment](https://github.com/k3s-io/cluster-api-k3s/issues/89#issuecomment-1932037119), it would be more explicit to have two dedicated fields in the server config:
1. `disableCloudProvider` to add the `--disable-cloud-provider` feature flag on k3s.
2. `cloudProviderName` to set an explicit cloud provider name.

The `DisableExternalCloudProvider` flag should be deprecated in the [upcoming v1beta2](https://github.com/k3s-io/cluster-api-k3s/pull/88) version.

An equivalent config would then be:
```yaml
serverConfig:
   disableCloudProvider: true
   cloudProviderName: external
```
