### ISSUE TITLE
Visualizer could not load cluster, need to enable default webhook

### ISSUE THREAD

**Issue by nasusoba** [k3s-io/cluster-api-k3s#110]
I am using [cluster api visualizer](https://github.com/Jont828/cluster-api-visualizer) to help with debugging. But I find that after upgrading to v1beta2, the visualizer could not load the cluster. It seems that the commented line must be added to fix.
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KThreesControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${NAMESPACE}
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: ${CLUSTER_NAME}-control-plane
      # namespace: ${NAMESPACE}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
  kthreesConfigSpec:
    serverConfig:
      tlsSan:
        - 0.0.0.0
```

What kubeadm capi does is to introduce the default webhook to set the namespace if it does not present ([ref](https://github.com/kubernetes-sigs/cluster-api/blob/180b50f9828adda2eba27bbf66d8ca9a07f3942f/controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go#L80)). I tried with the default webhook([commit](https://github.com/nasusoba/cluster-api-k3s/commit/a170d1b133ee8fc01b8053b1be656ceebc75db49)), but it seems that default webhook is not functioning?? Any idea??
