### ISSUE TITLE
KThreesControlPlane ServerConfig always reverts to defaults

### ISSUE THREAD

**Issue by anmazzotti** [k3s-io/cluster-api-k3s#120]
Using the `v1beta2` and configuring for example:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KThreesControlPlane
metadata:
  name: k3s-control-plane
  namespace: default
spec:
  kthreesConfigSpec:
    serverConfig:
      disableCloudController: false
      cloudProviderName: ""
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: InfraMachineTemplate
      name: infra-cluster-k3s-control-plane
  replicas: 1
  version: v1.28.5+k3s1
```

After applying this config, the KThreesControlPlane defaults back to:

```
        serverConfig:
          cloudProviderName: external
          disableCloudController: true
```

This was reported in the Slack channel in [this thread](https://kubernetes.slack.com/archives/C051K6ADDQB/p1716371033673299).
