### ISSUE TITLE
spec.kthreesConfigSpec.serverConfig.disableCloudController decoding error

### ISSUE THREAD

**Issue by VestigeJ** [k3s-io/cluster-api-k3s#143]
$ k apply -f k3s-cluster.yaml
```
awsmachinetemplate.infrastructure.cluster.x-k8s.io/justjustin-md-0 unchanged
awsmachinetemplate.infrastructure.cluster.x-k8s.io/justjustin-control-plane unchanged
cluster.cluster.x-k8s.io/justjustin unchanged
awscluster.infrastructure.cluster.x-k8s.io/justjustin configured
machinedeployment.cluster.x-k8s.io/justjustin-md-0 unchanged
kthreesconfigtemplate.bootstrap.cluster.x-k8s.io/justjustin-md-0 unchanged
Error from server (BadRequest): error when creating "k3s-cluster.yaml": KThreesControlPlane in version "v1beta1" cannot be handled as a KThreesControlPlane: strict decoding error: unknown field "spec.kthreesConfigSpec.serverConfig.disableCloudController"
```

$ ke kthreescontrolplane.spec.kthreesConfigSpec.serverConfig.disableCloudController
```
GROUP:      controlplane.cluster.x-k8s.io
KIND:       KThreesControlPlane
VERSION:    v1beta2

FIELD: disableCloudController <boolean>


DESCRIPTION:
    DisableCloudController disables k3s default cloud controller manager.
    (default: true)
```

$ cat k3s-cluster.yaml 

```
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KThreesControlPlane
metadata:
  name: just-a-control-plane
  namespace: aws
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSMachineTemplate
    name: just-a-control-plane
  kthreesConfigSpec:
    agentConfig:
      nodeName: "{{ ds.meta_data.local_hostname }}"
    serverConfig:
      disableCloudController: false
  replicas: 1
  version: v1.31.1+k3s1
---
```
