### ISSUE TITLE
User setup

### ISSUE THREAD

**Issue by luisdavim** [k3s-io/cluster-api-k3s#76]
kubeadm suports this https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/templates/cluster-template.yaml#L184

```yaml
users:
    - name: capv
      sshAuthorizedKeys:
      - '${VSPHERE_SSH_AUTHORIZED_KEY}'
      sudo: ALL=(ALL) NOPASSWD:ALL
```

it would be nice to have something similar in the `KThreesControlPlane`

see: https://github.com/kubernetes-sigs/cluster-api/blob/b587ff982f33a7d22d32991ebbeb9ea20e3be888/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L533
